### ISSUE TITLE
Issue trying to find SubMchId in WeChat

### ISSUE THREAD

**Issue by bigdoods** [verystar/wepay#1]
Hi, 

I am trying to use your SDK but I cant find the value of ```SubMchId``` in weChat vendor platform. Can you help please?

**Comment by fifsky** [comment]
@bigdoods 

Hi，

`SubMchId` is wechat pament service providers parameter, If you is general merchants, This parameter is not required

```
pay := wepay.NewClient(func(c *wepay.Client) {
    c.AppId = "xxxxxx"
    c.MchId = "123123123"
    c.ApiKey = "12313123123"
})
```

see https://github.com/verystar/wepay/blob/master/client.go#L183

**Comment by bigdoods** [comment]
We are trying to use the unified order API for weChat in-app payment.

**Comment by fifsky** [comment]
@bigdoods    
Sorry,weChat in-app payment. We don't know much about it yet. We mainly deal with weChat `micropay`
